#!/usr/bin/env python3
"""Exports the ROUTED carrier board (build/pg1-carrier.kicad_pcb) for the plugin's board simulator:
10-Carla-Plugin/Source/sim/BoardData.h

Everything comes from the real copper, not from carrier.py: every part and pad with its net, every track and via
(for drawing the current flow), and the copper ISLAND each pad sits on (found by walking the copper item by item, so
a net whose copper is split shows up as two islands = an open, and copper of two nets touching = a short).

    python3 board_export.py
"""
import os, sys
import pcbnew as K

HERE = os.path.dirname(os.path.abspath(__file__))
PCB = os.path.join(HERE, "build", "pg1-carrier.kicad_pcb")
OUT = os.path.join(os.path.dirname(HERE), "10-Carla-Plugin", "Source", "sim", "BoardData.h")


def mm(v):
    return round(K.ToMM(v), 3)


def main():
    b = K.LoadBoard(PCB)
    b.BuildConnectivity()
    conn = b.GetConnectivity()
    nets = sorted({p.GetNetname() for fp in b.GetFootprints() for p in fp.Pads() if p.GetNetname()})
    net_id = {n: i for i, n in enumerate(nets)}

    # copper islands: walk from each pad through everything its copper touches
    island_of, islands, shorts = {}, 0, set()
    pads = [p for fp in b.GetFootprints() for p in fp.Pads()]
    key = lambda it: it.m_Uuid.AsString()
    for p in pads:
        if key(p) in island_of or not p.GetNetname():
            continue
        stack, seen = [p], {key(p)}
        while stack:
            it = stack.pop()
            island_of[key(it)] = islands
            for nb in conn.GetConnectedItems(it):
                k = key(nb)
                if k in seen:
                    continue
                if nb.GetNetname() != p.GetNetname():   # copper of another net touching this one
                    shorts.add(tuple(sorted((p.GetNetname(), nb.GetNetname()))))
                    continue
                seen.add(k)
                stack.append(nb)
        islands += 1

    parts, padrows = [], []
    for fp in sorted(b.GetFootprints(), key=lambda f: f.GetReference()):
        fp.BuildCourtyardCaches()
        bb = fp.GetCourtyard(K.F_CrtYd).BBox()
        p0 = len(padrows)
        for p in sorted(fp.Pads(), key=lambda q: q.GetNumber()):
            pos, sz = p.GetPosition(), p.GetSize(K.F_Cu)
            tht = 1 if p.GetAttribute() == K.PAD_ATTRIB_PTH else 0
            n = p.GetNetname()
            padrows.append((fp.GetReference(), p.GetNumber(), net_id.get(n, -1), mm(pos.x), mm(pos.y), mm(sz.x), mm(sz.y), tht,
                            island_of.get(key(p), -1)))
        parts.append((fp.GetReference(), fp.GetValue(), fp.GetFPID().GetLibItemName().wx_str(), mm(fp.GetPosition().x),
                      mm(fp.GetPosition().y), round(fp.GetOrientationDegrees(), 1), mm(bb.GetLeft()), mm(bb.GetTop()),
                      mm(bb.GetRight()), mm(bb.GetBottom()), p0, len(padrows) - p0))

    tracks, vias = [], []
    for t in b.GetTracks():
        n = net_id.get(t.GetNetname(), -1)
        if isinstance(t, K.PCB_VIA):
            vias.append((mm(t.GetPosition().x), mm(t.GetPosition().y), mm(t.GetWidth(K.F_Cu)), n))
        else:
            s, e = t.GetStart(), t.GetEnd()
            tracks.append((mm(s.x), mm(s.y), mm(e.x), mm(e.y), mm(t.GetWidth()), n, 0 if t.GetLayer() == K.F_Cu else 1))
    edge = b.GetBoardEdgesBoundingBox()

    q = lambda s: '"' + s.replace('"', '\\"') + '"'
    L = ["// GENERATED by 12-Carrier-Board/board_export.py from the routed board. Do not edit.",
         "#pragma once", "#include <cstdint>", "namespace pgsim {",
         "struct BPart { const char* ref; const char* value; const char* fp; float x, y, rot, bx0, by0, bx1, by1; int pad0, npads; };",
         "struct BPad { const char* ref; const char* num; int net; float x, y, w, h; uint8_t tht; int island; };",
         "struct BTrack { float x1, y1, x2, y2, w; int net; uint8_t layer; };",
         "struct BVia { float x, y, d; int net; };",
         f"constexpr int kNets = {len(nets)}, kParts = {len(parts)}, kPads = {len(padrows)}, kTracks = {len(tracks)}, "
         f"kVias = {len(vias)}, kIslands = {islands}, kCopperShorts = {len(shorts)};",
         f"constexpr float kBoardX0 = {mm(edge.GetLeft())}f, kBoardY0 = {mm(edge.GetTop())}f, "
         f"kBoardX1 = {mm(edge.GetRight())}f, kBoardY1 = {mm(edge.GetBottom())}f;",
         "static const char* const kNetNames[kNets] = {" + ", ".join(q(n) for n in nets) + "};",
         "static const BPart kBParts[kParts] = {"]
    L += ["    {%s, %s, %s, %gf, %gf, %gf, %gf, %gf, %gf, %gf, %d, %d}," % (q(r), q(v), q(f), *rest) for r, v, f, *rest in parts]
    L += ["};", "static const BPad kBPads[kPads] = {"]
    L += ["    {%s, %s, %d, %gf, %gf, %gf, %gf, %d, %d}," % (q(r), q(n), *rest) for r, n, *rest in padrows]
    L += ["};", "static const BTrack kBTracks[kTracks] = {"]
    L += ["    {%gf, %gf, %gf, %gf, %gf, %d, %d}," % t for t in tracks]
    L += ["};", "static const BVia kBVias[kVias > 0 ? kVias : 1] = {"]
    L += ["    {%gf, %gf, %gf, %d}," % v for v in vias] or ["    {0, 0, 0, -1},"]
    L += ["};", "} // namespace pgsim", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write("\n".join(L))
    split = {}
    for r in padrows:
        if r[2] >= 0:
            split.setdefault(r[2], set()).add(r[8])
    opens = [nets[n] for n, s in split.items() if len(s) > 1]
    print(f"{OUT}: {len(parts)} parts, {len(padrows)} pads, {len(nets)} nets, {len(tracks)} tracks, {len(vias)} vias, "
          f"{islands} islands; split nets (opens): {opens or 'none'}; copper shorts: {sorted(shorts) or 'none'}")


if __name__ == "__main__":
    main()
