#!/usr/bin/env python3
"""Seed3 cost of each stage on its own (emulated Cortex-M7): runs bench_main once per stage."""
import os, sys
sys.argv = ["seed3_load.py"]
src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed3_load.py")).read()
src = src[:src.index('pc = run_until(sym["_start"]')]
g = {"__name__": "lib", "__file__": __file__}
exec(compile(src, "seed3_load.py", "exec"), g)
from unicorn.arm_const import UC_ARM_REG_R0, UC_ARM_REG_R1, UC_ARM_REG_R2, UC_ARM_REG_R3, UC_ARM_REG_SP, UC_ARM_REG_LR
from unicorn import UC_HOOK_CODE
names = ["hum", "eq", "comp", "clarity", "sat", "deharsh", "safety", "vis", "input", "health", "takeback", "width", "loud", "config", "mband", "pid"]
mu, sym, count, hook, LIBM = g["mu"], g["sym"], g["count"], g["hook"], g["LIBM"]
def cost(mask):
    for seg in g["elf"].iter_segments():
        if seg["p_type"] == "PT_LOAD" and seg["p_filesz"]:
            mu.mem_write(seg["p_paddr"], seg.data())
    mu.mem_write(sym["__bss_start__"], b"\0" * (sym["__bss_end__"] - sym["__bss_start__"]))   # fresh .bss (zeroed)
    for r, v in ((UC_ARM_REG_R0, 200), (UC_ARM_REG_R1, 10), (UC_ARM_REG_R2, 0), (UC_ARM_REG_R3, mask & 0xFFFFFFFF)):
        mu.reg_write(r, v)
    mu.reg_write(UC_ARM_REG_SP, 0x20000000 + (1 << 20) - 64), mu.reg_write(UC_ARM_REG_LR, sym["mark_done"] | 1)
    mu.emu_start(sym["bench_main"] | 1, sym["mark_audio_start"] & ~1)
    count.update(n=0, lib=0, calls={})
    h = mu.hook_add(UC_HOOK_CODE, hook); mu.ctl_flush_tb(); count["on"] = True
    mu.emu_start(sym["mark_audio_start"] | 1, sym["mark_audio_end"] & ~1)
    count["on"] = False; mu.hook_del(h); mu.ctl_flush_tb()
    return (count["n"] + sum(LIBM[f] * n for f, n in count["calls"].items())) / 10 / 48
base = cost(1 << 6) # safety only (always on)
print(f"{'safety + the frame (always)':30s} {base:7.0f} instr/sample  {100 * base / 10000:5.1f} %")
costs = [0] * 16
for t in range(16):
    if names[t] in ("safety", "vis", "health", "config"):
        continue
    c = cost((1 << 6) | (1 << t)) - base
    costs[t] = max(0, round(c))
    print(f"{names[t]:30s} {c:7.0f} instr/sample  {100 * c / 10000:5.1f} %", flush=True)
# the plugin's Seed3 load estimate uses this table (so the health tab's cpu check behaves as on the pedal)
hdr = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "PG-Pedal-1", "10-Carla-Plugin", "Source", "Seed3Costs.h")
with open(hdr, "w") as f:
    f.write("// Generated by _Tools/seed3-bench/stages.py - don't edit by hand. Measured on an emulated Cortex-M7 with the\n")
    f.write("// firmware's own compiler flags: instructions per sample for the always-on part, and what each tab adds.\n")
    f.write("#pragma once\nnamespace seed3\n{\n")
    f.write(f"constexpr int kBase = {round(base)};\n")
    f.write("constexpr int kStage[16] = {" + ", ".join(str(c) for c in costs) + "}; // in pg::Tab order\n")
    f.write("constexpr float kClocksPerInstr = 1.2f; // Cortex-M7 at 480 MHz on this kind of code: ~1.0 typical, 1.5 pessimistic\n")
    f.write("constexpr float kClocksPerSample = 480e6f / 48000.f;\n}\n")
print("wrote", os.path.normpath(hdr))
