// Generated by _Tools/seed3-bench/stages.py - don't edit by hand. Measured on an emulated Cortex-M7 with the
// firmware's own compiler flags: instructions per sample for the always-on part, and what each tab adds.
#pragma once
namespace seed3
{
constexpr int kBase = 1841;
constexpr int kStage[16] = {242, 450, 199, 909, 336, 364, 0, 0, 65, 0, 243, 82, 129, 0, 818, 221}; // in pg::Tab order
constexpr float kClocksPerInstr = 1.2f; // Cortex-M7 at 480 MHz on this kind of code: ~1.0 typical, 1.5 pessimistic
constexpr float kClocksPerSample = 480e6f / 48000.f;
}
